### ISSUE TITLE
Wildcards for fastq files

### ISSUE THREAD

**Issue by JFK24** [zhxiaokang/RASflow#13] opened 2020-07-01 14:01 UTC
File path built with wildcards do not recognize "sample1.fastq.gz" as a single file if "sample10.fastq.gz" is in same directory, instead it returns a list with the 2 files. 

My way to fix it:

IN align_count_genome.rules AND quantify_trans.rules
CHANGE
`shell("scp -i {params.key} {params.input_path}/{wildcards.sample}*.f*q.gz {output.read}")`
TO 
`shell("scp -i {params.key} {params.input_path}/{wildcards.sample}.f*q.gz {output.read}")`

**Comment by zhxiaokang** [comment] 2020-07-03 15:58
Well spotted! It's a good point that I didn't think of. Thank you!

But your solution misses this type of file naming: `{wildcards.sample}.something_else.f*q.gz`. And this is the reason I put a `*` after `{wildcards.sample}`. But now I see the issue caused by the `*`.

I don't have a better solution so far. I've posted the question on [StackExchange](https://unix.stackexchange.com/questions/596551/how-to-use-shell-glob-as-what-does-in-regular-expression)

Let's see whether we can get a better solution.

**Comment by zhxiaokang** [comment] 2020-07-06 10:00
Got some kind suggestions from [StackExchange](https://unix.stackexchange.com/questions/596551/how-to-use-shell-glob-as-what-does-in-regular-expression). I found `shopt -s extglob` very simple and useful. Could you try it out to see if it works for you?
```
rule getReads:
    output:
        read = temp(intermediate_path + "/reads/{sample}.fastq.gz")
    params:
        key = key,
        input_path = input_path
    shell:
        """
        shopt -s extglob
        scp -i {params.key} {params.input_path}/{wildcards.sample}?(.*).f*q.gz {output.read}
        """
```

**Comment by JFK24** [comment] 2020-07-06 20:59
It works for my case, thanks!

**Comment by zhxiaokang** [comment] 2020-07-07 09:13
Fixed with [commit](https://github.com/zhxiaokang/RASflow/commit/e7d6a8f1da4a1aa7af3887170d1b4acb3eb298fa)

**Closed by zhxiaokang** 2020-07-07 09:13 UTC
